version: "2.2"

services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: scetts/tts-server:v3
        cpus: 1
        restart: unless-stopped
        environment:
            - "TTS_MODEL_FILE=/data/models/model.onnx"
            - "TTS_MODEL_CONFIG=/data/models/model.onnx.json"
        volumes:
            - "./data/src:/data/src"
            - "./data/models:/data/models"
        ports: 
            - "5000:5000"